# =============================================================================
# WireGuard Tasks - Linux
# =============================================================================
# VPN server configuration
# =============================================================================

- name: Install WireGuard
  apt:
    name: wireguard
    state: present

- name: Deploy WireGuard configuration
  template:
    src: templates/nsa/wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: '0600'
  notify: Restart wireguard

- name: Enable IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- name: Enable WireGuard
  systemd:
    name: wg-quick@wg0
    enabled: yes
    state: started
